### ISSUE TITLE
Ellipse support

### ISSUE THREAD

**Issue by denysvitali** [denysvitali/squid_decoder#1]
- [x] Add line stroke size support
- [x] Fix radius line (see photo attached)

Radius line:
![screenshot from 2017-05-22 23-38-54](https://cloud.githubusercontent.com/assets/4939519/26329576/2153af0c-3f48-11e7-93b6-b4adf6d486b8.png)

**Comment by denysvitali** [comment]
New result:
![screenshot from 2017-05-23 11-40-41](https://cloud.githubusercontent.com/assets/4939519/26348339/bbccc532-3fac-11e7-8c18-792fec69b861.png)

**Comment by haxelion** [comment]
Looks very good :smile:
