### ISSUE TITLE
Cannot unzip papyrus.bak

### ISSUE THREAD

**Issue by volkerkarle** [denysvitali/squid_decoder#4]
/edit: It was my problem, it just works fine. Thanks a lot!

Hi there,
When I run the command unzip papyrus.bak I get the following error:
 
Archive:  papyrus.bak       
  End-of-central-directory signature not found.  Either this file is not                                
  a zipfile, or it constitutes one disk of a multi-part archive.  In the                                
  latter case the central directory and zipfile comment will be found on                                
  the last disk(s) of this archive.                 
unzip:  cannot find zipfile directory in one of papyrus.bak or                                            
        papyrus.bak.zip, and cannot find squid.bak.ZIP, period.

What could be the problem?

**Comment by denysvitali** [comment]
Can you try by renaming the `papyrus.bak` file into `papyrus.zip` and extracting it again with `unzip papyrus.zip`?
If that doesn't work, can you attach here the file (or send it to me via email at denys@denv.it if you don't want to make it publically available)?  
  
What OS are you using? What's the unzip version?
